apiVersion: 1

datasources:
  - name: Demo Prometheus
    uid: prometheus-demo
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST
